set (TARGET_NAME krb5)

set (TARGET_SRC
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/acache.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/add_et_list.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/addr_families.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/appdefault.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/asn1_glue.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/auth_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/authdata.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/build_ap_req.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/build_auth.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/cache.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/changepw.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/codec.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/config_file.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/constants.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/convert_creds.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/copy_host_realm.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crc.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/creds.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-aes.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-algs.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-arcfour.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-des3.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-des.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-des-common.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-evp.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-null.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-pk.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/crypto-rand.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/data.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/eai_to_heim_errno.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/error_string.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/expand_hostname.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/fcache.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/free.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/free_host_realm.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/generate_seq_number.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/generate_subkey.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/get_addrs.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/get_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/get_default_principal.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/get_default_realm.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/get_for_creds.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/get_host_realm.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/get_in_tkt.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/get_port.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/init_creds.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/init_creds_pw.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/kcm.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/keyblock.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/keytab.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/keytab_any.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/keytab_file.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/keytab_memory.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/keytab_keyfile.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/krbhst.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/log.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/mcache.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/misc.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/mk_error.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/mk_priv.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/mk_rep.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/mk_req.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/mk_req_ext.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/mit_glue.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/n-fold.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/padata.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/pkinit.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/principal.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/prog_setup.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/pac.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/pcache.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/prompter_posix.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/rd_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/rd_error.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/rd_priv.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/rd_rep.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/rd_req.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/replay.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/salt.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/salt-aes.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/salt-arcfour.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/salt-des3.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/salt-des.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/send_to_kdc.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/set_default_realm.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/store.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/store-int.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/store_emem.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/store_fd.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/store_mem.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/ticket.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/time.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/transited.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/version.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/warn.c
     ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/krb5/krb5_err.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/aname_to_localname.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/kuserok.c
     ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/krb5/heim_err.c
     ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/krb5/k524_err.c
     ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/krb5/krb_err.c
     ${SMB_SRC_ROOT}/source4/heimdal_build/krb5-glue.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/expand_path.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/plugin.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5/context.c)

add_library (${TARGET_NAME}_obj OBJECT ${TARGET_SRC})

target_include_directories (${TARGET_NAME}_obj
                            PRIVATE
                                ${SMB_SRC_ROOT}/source4/heimdal_build
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal_build
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/krb5
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/asn1
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/asn1
                                ${SMB_SRC_ROOT}/source4/heimdal/include
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/include
                                ${SMB_SRC_ROOT}/include/public
                                ${SMB_SRC_ROOT}/bin/default/include/public
                                ${SMB_SRC_ROOT}/source4
                                ${SMB_SRC_ROOT}/bin/default/source4
                                ${SMB_SRC_ROOT}/lib
                                ${SMB_SRC_ROOT}/bin/default/lib
                                ${SMB_SRC_ROOT}/source4/lib
                                ${SMB_SRC_ROOT}/bin/default/source4/lib
                                ${SMB_SRC_ROOT}/source4/include
                                ${SMB_SRC_ROOT}/bin/default/source4/include
                                ${SMB_SRC_ROOT}/include
                                ${SMB_SRC_ROOT}/bin/default/include
                                ${SMB_SRC_ROOT}/lib/replace
                                ${SMB_SRC_ROOT}/bin/default/lib/replace
                                ${SMB_SRC_ROOT}/.
                                ${SMB_SRC_ROOT}/bin/default/
                                ${SMB_SRC_ROOT}/source4/heimdal/base
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/base
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/hx509
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/hx509
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/wind
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/wind
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/roken
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/roken
                                ${SMB_SRC_ROOT}/source4/heimdal_build/include
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal_build/include
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/hcrypto
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/hcrypto
                                ${SMB_SRC_ROOT}/source4/heimdal/lib
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/hcrypto/libtommath
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/hcrypto/libtommath
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/com_err
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/com_err)

target_compile_definitions (${TARGET_NAME}_obj
                            PRIVATE
                                _SAMBA_BUILD_=4
                                HAVE_CONFIG_H=1
                                _GNU_SOURCE=1
                                _XOPEN_SOURCE_EXTENDED=1
                                __STDC_WANT_LIB_EXT1__=1
                                _REENTRANT
                                _POSIX_PTHREAD_SEMANTICS
                                STATIC_krb5_MODULES=NULL
                                "STATIC_krb5_MODULES_PROTO=extern void __krb5_dummy_module_proto(void)"
                                BINDIR="/bin"
                                SBINDIR="/bin"
                                LIBDIR="/usr/local/samba/lib"
                                LIBEXECDIR="/bin"
                                STATIC_HEIMDAL_CONFIG_MODULES=NULL
                                "STATIC_HEIMDAL_CONFIG_MODULES_PROTO=extern void __HEIMDAL_CONFIG_dummy_module_proto(void)"
)

target_compile_options (${TARGET_NAME}_obj
                        PRIVATE -MMD
                                -fPIC
                                -fstack-protector-strong
                                ${GCCDEFS}
                                -Wno-error=discarded-qualifiers
                                -Wno-error=cast-qual
                                -Wno-error=missing-field-initializers
                                -Wno-error=shadow
                                -Wno-error=implicit-fallthrough
                                -Wno-error=enum-compare
                                -Wno-error=unused-but-set-variable
                                -Wno-error=unused-const-variable
                                -Wno-error=unused-variable
                                -Wno-error=unused-result)
