set (TARGET_NAME smbconf)

set (TARGET_SRC
     ${SMB_SRC_ROOT}/source3/param/loadparm.c
     ${SMB_SRC_ROOT}/source3/lib/sharesec.c
     ${SMB_SRC_ROOT}/source3/lib/ldap_debug_handler.c
     ${SMB_SRC_ROOT}/source3/lib/util_names.c
     ${SMB_SRC_ROOT}/source3/registry/reg_backend_smbconf.c
     ${SMB_SRC_ROOT}/source3/registry/reg_init_smbconf.c
     ${SMB_SRC_ROOT}/source3/registry/reg_util_token.c
     ${SMB_SRC_ROOT}/source3/registry/reg_api_util.c
     ${SMB_SRC_ROOT}/bin/default/librpc/gen_ndr/ndr_messaging.c
     ${SMB_SRC_ROOT}/source3/param/loadparm_ctx.c
     ${SMB_SRC_ROOT}/source3/param/util.c
     ${SMB_SRC_ROOT}/source3/lib/util_tdb.c
     ${SMB_SRC_ROOT}/lib/async_req/async_sock.c
     ${SMB_SRC_ROOT}/source3/lib/dbwrap/dbwrap_open.c
     ${SMB_SRC_ROOT}/source3/lib/dbwrap/dbwrap_watch.c
     ${SMB_SRC_ROOT}/source3/lib/g_lock.c
     ${SMB_SRC_ROOT}/source3/registry/reg_api.c
     ${SMB_SRC_ROOT}/source3/registry/reg_dispatcher.c
     ${SMB_SRC_ROOT}/source3/registry/reg_cachehook.c
     ${SMB_SRC_ROOT}/source3/registry/reg_objects.c
     ${SMB_SRC_ROOT}/source3/registry/reg_util_internal.c
     ${SMB_SRC_ROOT}/source3/lib/util_nttoken.c
     ${SMB_SRC_ROOT}/source3/registry/reg_backend_db.c
     ${SMB_SRC_ROOT}/source3/registry/reg_parse_internal.c
     ${SMB_SRC_ROOT}/source3/registry/reg_parse.c
     ${SMB_SRC_ROOT}/source3/lib/srprs.c
     ${SMB_SRC_ROOT}/source3/registry/reg_init_basic.c
     ${SMB_SRC_ROOT}/source3/lib/version.c
     ${SMB_SRC_ROOT}/lib/smbconf/smbconf.c
     ${SMB_SRC_ROOT}/lib/smbconf/smbconf_txt.c
     ${SMB_SRC_ROOT}/lib/smbconf/smbconf_util.c
     ${SMB_SRC_ROOT}/source3/lib/messages.c
     ${SMB_SRC_ROOT}/source3/lib/util_cluster.c
     ${SMB_SRC_ROOT}/source3/lib/id_cache.c
     ${SMB_SRC_ROOT}/source3/lib/serverid.c
     ${SMB_SRC_ROOT}/source3/lib/server_id_watch.c
     ${SMB_SRC_ROOT}/source3/lib/server_id_db_util.c
     ${SMB_SRC_ROOT}/source3/lib/addrchange.c
     ${SMB_SRC_ROOT}/lib/util/debug_s3.c
     ${SMB_SRC_ROOT}/source3/lib/dumpcore.c
     ${SMB_SRC_ROOT}/source3/lib/interface.c
     ${SMB_SRC_ROOT}/source3/lib/username.c
     ${SMB_SRC_ROOT}/source3/lib/smbrun.c
     ${SMB_SRC_ROOT}/source3/lib/wins_srv.c
     ${SMB_SRC_ROOT}/source3/lib/substitute.c
     ${SMB_SRC_ROOT}/source3/lib/substitute_generic.c
     ${SMB_SRC_ROOT}/source3/lib/ms_fnmatch.c
     ${SMB_SRC_ROOT}/source3/lib/tallocmsg.c
     ${SMB_SRC_ROOT}/source3/lib/dmallocmsg.c
     ${SMB_SRC_ROOT}/source3/lib/gencache.c
     ${SMB_SRC_ROOT}/source3/lib/util_event.c
     ${SMB_SRC_ROOT}/source3/lib/global_contexts.c
     ${SMB_SRC_ROOT}/source3/lib/server_prefork.c
     ${SMB_SRC_ROOT}/source3/lib/server_prefork_util.c
     ${SMB_SRC_ROOT}/source3/lib/ldap_escape.c
     ${SMB_SRC_ROOT}/source3/lib/system_smbd.c
     ${SMB_SRC_ROOT}/source3/lib/audit.c
     ${SMB_SRC_ROOT}/source3/lib/idmap_cache.c
     ${SMB_SRC_ROOT}/source3/lib/namemap_cache.c
     ${SMB_SRC_ROOT}/source3/lib/util_ea.c
     ${SMB_SRC_ROOT}/source3/lib/background.c
     ${SMB_SRC_ROOT}/lib/util/util_pw.c
     ${SMB_SRC_ROOT}/bin/default/librpc/gen_ndr/ndr_server_id.c
     ${SMB_SRC_ROOT}/source3/lib/system.c
     ${SMB_SRC_ROOT}/source3/lib/sendfile.c
     ${SMB_SRC_ROOT}/source3/lib/recvfile.c
     ${SMB_SRC_ROOT}/source3/lib/time.c
     ${SMB_SRC_ROOT}/source3/lib/util_sid.c
     ${SMB_SRC_ROOT}/source3/lib/util_specialsids.c
     ${SMB_SRC_ROOT}/source3/lib/util_file.c
     ${SMB_SRC_ROOT}/source3/lib/util.c
     ${SMB_SRC_ROOT}/source3/lib/util_path.c
     ${SMB_SRC_ROOT}/source3/lib/util_matching.c
     ${SMB_SRC_ROOT}/source3/lib/util_procid.c
     ${SMB_SRC_ROOT}/source3/lib/util_sock.c
     ${SMB_SRC_ROOT}/source3/lib/util_tsock.c
     ${SMB_SRC_ROOT}/source3/lib/util_transfer_file.c
     ${SMB_SRC_ROOT}/source3/lib/util_macstreams.c
     ${SMB_SRC_ROOT}/source3/libsmb/errormap.c
     ${SMB_SRC_ROOT}/source3/libsmb/smberr.c
     ${SMB_SRC_ROOT}/source3/lib/errmap_unix.c
     ${SMB_SRC_ROOT}/source3/lib/smbconf/smbconf_init.c
     ${SMB_SRC_ROOT}/source3/lib/smbconf/smbconf_reg.c)

add_library (${TARGET_NAME}_obj OBJECT ${TARGET_SRC})

target_include_directories (${TARGET_NAME}_obj
                            PRIVATE ${SMB_SRC_ROOT}/source3
                                    ${SMB_SRC_ROOT}/bin/default/source3
                                    ${SMB_SRC_ROOT}/source3/include
                                    ${SMB_SRC_ROOT}/bin/default/source3/include
                                    ${SMB_SRC_ROOT}/source3/lib
                                    ${SMB_SRC_ROOT}/bin/default/source3/lib
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/com_err
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/com_err
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/krb5
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/gssapi
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi/gssapi
                                    ${SMB_SRC_ROOT}/source4/heimdal_build/include
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal_build/include
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/asn1
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/asn1
                                    ${SMB_SRC_ROOT}/lib/tdb/include
                                    ${SMB_SRC_ROOT}/bin/default/lib/tdb/include
                                    ${SMB_SRC_ROOT}/lib/tevent
                                    ${SMB_SRC_ROOT}/bin/default/lib/tevent
                                    ${SMB_SRC_ROOT}/lib/talloc
                                    ${SMB_SRC_ROOT}/bin/default/lib/talloc
                                    ${SMB_SRC_ROOT}/lib/popt
                                    ${SMB_SRC_ROOT}/bin/default/lib/popt
                                    ${SMB_SRC_ROOT}/include/public
                                    ${SMB_SRC_ROOT}/bin/default/include/public
                                    ${SMB_SRC_ROOT}/source4
                                    ${SMB_SRC_ROOT}/bin/default/source4
                                    ${SMB_SRC_ROOT}/lib
                                    ${SMB_SRC_ROOT}/bin/default/lib
                                    ${SMB_SRC_ROOT}/source4/lib
                                    ${SMB_SRC_ROOT}/bin/default/source4/lib
                                    ${SMB_SRC_ROOT}/source4/include
                                    ${SMB_SRC_ROOT}/bin/default/source4/include
                                    ${SMB_SRC_ROOT}/include
                                    ${SMB_SRC_ROOT}/bin/default/include
                                    ${SMB_SRC_ROOT}/lib/replace
                                    ${SMB_SRC_ROOT}/bin/default/lib/replace
                                    ${SMB_SRC_ROOT}/.
                                    ${SMB_SRC_ROOT}/bin/default/
                                    ${SMB_SRC_ROOT}/librpc
                                    ${SMB_SRC_ROOT}/bin/default/librpc
                                    ${SMB_SRC_ROOT}/libcli/registry
                                    ${SMB_SRC_ROOT}/bin/default/libcli/registry
                                    ${SMB_SRC_ROOT}/source3/param
                                    ${SMB_SRC_ROOT}/bin/default/source3/param
                                    ${SMB_SRC_ROOT}/lib/messaging
                                    ${SMB_SRC_ROOT}/bin/default/lib/messaging
                                    ${SMB_SRC_ROOT}/lib/dbwrap
                                    ${SMB_SRC_ROOT}/bin/default/lib/dbwrap
                                    ${SMB_SRC_ROOT}/lib/util/charset
                                    ${SMB_SRC_ROOT}/bin/default/lib/util/charset
                                    ${SMB_SRC_ROOT}/libcli/security
                                    ${SMB_SRC_ROOT}/bin/default/libcli/security
                                    ${SMB_SRC_ROOT}/lib/pthreadpool
                                    ${SMB_SRC_ROOT}/bin/default/lib/pthreadpool
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/roken
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/roken
                                    ${SMB_SRC_ROOT}/source4/heimdal/include
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/include
                                    ${SMB_SRC_ROOT}/source4/heimdal_build
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal_build
                                    ${SMB_SRC_ROOT}/lib/param
                                    ${SMB_SRC_ROOT}/bin/default/lib/param
                                    ${SMB_SRC_ROOT}/lib/crypto
                                    ${SMB_SRC_ROOT}/bin/default/lib/crypto
                                    ${SMB_SRC_ROOT}/dynconfig
                                    ${SMB_SRC_ROOT}/bin/default/dynconfig
                                    ${SMB_SRC_ROOT}/source4/lib/socket
                                    ${SMB_SRC_ROOT}/bin/default/source4/lib/socket
                                    ${SMB_SRC_ROOT}/libcli/util
                                    ${SMB_SRC_ROOT}/bin/default/libcli/util
                                    ${SMB_SRC_ROOT}/lib/socket
                                    ${SMB_SRC_ROOT}/bin/default/lib/socket
                                    ${SMB_SRC_ROOT}/lib/tdb
                                    ${SMB_SRC_ROOT}/bin/default/lib/tdb
                                    ${SMB_SRC_ROOT}/lib/tsocket
                                    ${SMB_SRC_ROOT}/bin/default/lib/tsocket
                                    ${SMB_SRC_ROOT}/source4/libcli
                                    ${SMB_SRC_ROOT}/bin/default/source4/libcli
                                    ${SMB_SRC_ROOT}/libcli/nbt
                                    ${SMB_SRC_ROOT}/bin/default/libcli/nbt
                                    ${SMB_SRC_ROOT}/source4/lib/events
                                    ${SMB_SRC_ROOT}/bin/default/source4/lib/events
                                    ${SMB_SRC_ROOT}/lib/async_req
                                    ${SMB_SRC_ROOT}/bin/default/lib/async_req
                                    ${SMB_SRC_ROOT}/lib/smbconf
                                    ${SMB_SRC_ROOT}/bin/default/lib/smbconf)

target_compile_definitions (${TARGET_NAME}_obj
                            PRIVATE
                                _SAMBA_BUILD_=4
                                HAVE_CONFIG_H=1
                                _GNU_SOURCE=1
                                _XOPEN_SOURCE_EXTENDED=1
                                __STDC_WANT_LIB_EXT1__=1
                                _REENTRANT
                                _POSIX_PTHREAD_SEMANTICS
                                STATIC_SMBCONF_PARAM_MODULES=NULL
                                "STATIC_SMBCONF_PARAM_MODULES_PROTO=extern void __SMBCONF_PARAM_dummy_module_proto(void)"
                                STATIC_REG_SMBCONF_MODULES=NULL
                                "STATIC_REG_SMBCONF_MODULES_PROTO=extern void __REG_SMBCONF_dummy_module_proto(void)"
                                STATIC_NDR_MESSAGING_MODULES=NULL
                                "STATIC_NDR_MESSAGING_MODULES_PROTO=extern void __NDR_MESSAGING_dummy_module_proto(void)"
                                STATIC_LOADPARM_CTX_MODULES=NULL
                                "STATIC_LOADPARM_CTX_MODULES_PROTO=extern void __LOADPARM_CTX_dummy_module_proto(void)"
                                STATIC_PARAM_UTIL_MODULES=NULL
                                "STATIC_PARAM_UTIL_MODULES_PROTO=extern void __PARAM_UTIL_dummy_module_proto(void)"
                                STATIC_tdb_wrap3_MODULES=NULL
                                "STATIC_tdb_wrap3_MODULES_PROTO=extern void __tdb_wrap3_dummy_module_proto(void)"
                                STATIC_LIBASYNC_REQ_MODULES=NULL
                                "STATIC_LIBASYNC_REQ_MODULES_PROTO=extern void __LIBASYNC_REQ_dummy_module_proto(void)"
                                STATIC_TDB_LIB_MODULES=NULL
                                "STATIC_TDB_LIB_MODULES_PROTO=extern void __TDB_LIB_dummy_module_proto(void)"
                                STATIC_SMBREGISTRY_MODULES=NULL
                                "STATIC_SMBREGISTRY_MODULES_PROTO=extern void __SMBREGISTRY_dummy_module_proto(void)"
                                STATIC_SAMBA_VERSION_MODULES=NULL
                                "STATIC_SAMBA_VERSION_MODULES_PROTO=extern void __SAMBA_VERSION_dummy_module_proto(void)"
                                STATIC_LIBSMBCONF_MODULES=NULL
                                "STATIC_LIBSMBCONF_MODULES_PROTO=extern void __LIBSMBCONF_dummy_module_proto(void)"
                                STATIC_samba3core_MODULES=NULL
                                "STATIC_samba3core_MODULES_PROTO=extern void __samba3core_dummy_module_proto(void)"
                                STATIC_UTIL_PW_MODULES=NULL
                                "STATIC_UTIL_PW_MODULES_PROTO=extern void __UTIL_PW_dummy_module_proto(void)"
                                STATIC_NDR_SERVER_ID_MODULES=NULL
                                "STATIC_NDR_SERVER_ID_MODULES_PROTO=extern void __NDR_SERVER_ID_dummy_module_proto(void)"
                                STATIC_samba3util_MODULES=NULL
                                "STATIC_samba3util_MODULES_PROTO=extern void __samba3util_dummy_module_proto(void)"
                                STATIC_errors3_MODULES=NULL
                                "STATIC_errors3_MODULES_PROTO=extern void __errors3_dummy_module_proto(void)"
                                STATIC_smbconf_MODULES=NULL
                                "STATIC_smbconf_MODULES_PROTO=extern void __smbconf_dummy_module_proto(void)"
)

target_compile_options (${TARGET_NAME}_obj PRIVATE -MMD -fPIC -fstack-protector-strong ${GCCDEFS})
