set (TARGET_NAME common-auth)

set (TARGET_SRC
     ${SMB_SRC_ROOT}/lib/audit_logging/audit_logging.c ${SMB_SRC_ROOT}/lib/util/util_str_escape.c
     ${SMB_SRC_ROOT}/auth/auth_sam_reply.c ${SMB_SRC_ROOT}/auth/wbc_auth_util.c
     ${SMB_SRC_ROOT}/auth/auth_log.c ${SMB_SRC_ROOT}/auth/auth_util.c)

add_library (${TARGET_NAME}_obj OBJECT ${TARGET_SRC})

target_include_directories (${TARGET_NAME}_obj
                            PRIVATE ${SMB_SRC_ROOT}/lib/audit_logging
                                    ${SMB_SRC_ROOT}/bin/default/lib/audit_logging
                                    ${SMB_SRC_ROOT}/include/public
                                    ${SMB_SRC_ROOT}/bin/default/include/public
                                    ${SMB_SRC_ROOT}/source4
                                    ${SMB_SRC_ROOT}/bin/default/source4
                                    ${SMB_SRC_ROOT}/lib
                                    ${SMB_SRC_ROOT}/bin/default/lib
                                    ${SMB_SRC_ROOT}/source4/lib
                                    ${SMB_SRC_ROOT}/bin/default/source4/lib
                                    ${SMB_SRC_ROOT}/source4/include
                                    ${SMB_SRC_ROOT}/bin/default/source4/include
                                    ${SMB_SRC_ROOT}/include
                                    ${SMB_SRC_ROOT}/bin/default/include
                                    ${SMB_SRC_ROOT}/lib/replace
                                    ${SMB_SRC_ROOT}/bin/default/lib/replace
                                    ${SMB_SRC_ROOT}/.
                                    ${SMB_SRC_ROOT}/bin/default/
                                    ${SMB_SRC_ROOT}/librpc
                                    ${SMB_SRC_ROOT}/bin/default/librpc
                                    ${SMB_SRC_ROOT}/lib/tevent
                                    ${SMB_SRC_ROOT}/bin/default/lib/tevent
                                    ${SMB_SRC_ROOT}/lib/util/charset
                                    ${SMB_SRC_ROOT}/bin/default/lib/util/charset
                                    ${SMB_SRC_ROOT}/lib/messaging
                                    ${SMB_SRC_ROOT}/bin/default/lib/messaging
                                    ${SMB_SRC_ROOT}/lib/dbwrap
                                    ${SMB_SRC_ROOT}/bin/default/lib/dbwrap
                                    ${SMB_SRC_ROOT}/libcli/security
                                    ${SMB_SRC_ROOT}/bin/default/libcli/security
                                    ${SMB_SRC_ROOT}/lib/pthreadpool
                                    ${SMB_SRC_ROOT}/bin/default/lib/pthreadpool
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/roken
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/roken
                                    ${SMB_SRC_ROOT}/source4/heimdal/include
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/include
                                    ${SMB_SRC_ROOT}/source4/heimdal_build/include
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal_build/include
                                    ${SMB_SRC_ROOT}/source4/heimdal_build
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal_build
                                    ${SMB_SRC_ROOT}/lib/param
                                    ${SMB_SRC_ROOT}/bin/default/lib/param
                                    ${SMB_SRC_ROOT}/lib/crypto
                                    ${SMB_SRC_ROOT}/bin/default/lib/crypto
                                    ${SMB_SRC_ROOT}/dynconfig
                                    ${SMB_SRC_ROOT}/bin/default/dynconfig
                                    ${SMB_SRC_ROOT}/source4/cluster
                                    ${SMB_SRC_ROOT}/bin/default/source4/cluster
                                    ${SMB_SRC_ROOT}/source4/lib/socket
                                    ${SMB_SRC_ROOT}/bin/default/source4/lib/socket
                                    ${SMB_SRC_ROOT}/libcli/util
                                    ${SMB_SRC_ROOT}/bin/default/libcli/util
                                    ${SMB_SRC_ROOT}/source4/lib/messaging
                                    ${SMB_SRC_ROOT}/bin/default/source4/lib/messaging
                                    ${SMB_SRC_ROOT}/lib/socket
                                    ${SMB_SRC_ROOT}/bin/default/lib/socket
                                    ${SMB_SRC_ROOT}/lib/tdb/include
                                    ${SMB_SRC_ROOT}/bin/default/lib/tdb/include
                                    ${SMB_SRC_ROOT}/lib/tdb
                                    ${SMB_SRC_ROOT}/bin/default/lib/tdb
                                    ${SMB_SRC_ROOT}/lib/tsocket
                                    ${SMB_SRC_ROOT}/bin/default/lib/tsocket
                                    ${SMB_SRC_ROOT}/source3
                                    ${SMB_SRC_ROOT}/bin/default/source3
                                    ${SMB_SRC_ROOT}/source3/include
                                    ${SMB_SRC_ROOT}/bin/default/source3/include
                                    ${SMB_SRC_ROOT}/source3/lib
                                    ${SMB_SRC_ROOT}/bin/default/source3/lib
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/com_err
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/com_err
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/krb5
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/gssapi
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi/gssapi
                                    ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/asn1
                                    ${SMB_SRC_ROOT}/source4/heimdal/lib/asn1
                                    ${SMB_SRC_ROOT}/lib/talloc
                                    ${SMB_SRC_ROOT}/bin/default/lib/talloc
                                    ${SMB_SRC_ROOT}/lib/popt
                                    ${SMB_SRC_ROOT}/bin/default/lib/popt
                                    ${SMB_SRC_ROOT}/source4/libcli
                                    ${SMB_SRC_ROOT}/bin/default/source4/libcli
                                    ${SMB_SRC_ROOT}/libcli/nbt
                                    ${SMB_SRC_ROOT}/bin/default/libcli/nbt
                                    ${SMB_SRC_ROOT}/source4/lib/events
                                    ${SMB_SRC_ROOT}/bin/default/source4/lib/events
                                    ${SMB_SRC_ROOT}/auth
                                    ${SMB_SRC_ROOT}/bin/default/auth
                                    ${SMB_SRC_ROOT}/source3/librpc
                                    ${SMB_SRC_ROOT}/bin/default/source3/librpc
                                    ${SMB_SRC_ROOT}/lib/compression
                                    ${SMB_SRC_ROOT}/bin/default/lib/compression)

target_compile_definitions (${TARGET_NAME}_obj
                            PRIVATE
                                _SAMBA_BUILD_=4
                                HAVE_CONFIG_H=1
                                _GNU_SOURCE=1
                                _XOPEN_SOURCE_EXTENDED=1
                                __STDC_WANT_LIB_EXT1__=1
                                _REENTRANT
                                _POSIX_PTHREAD_SEMANTICS
                                STATIC_audit_logging_MODULES=NULL
                                "STATIC_audit_logging_MODULES_PROTO=extern void __audit_logging_dummy_module_proto(void)"
                                STATIC_util_str_escape_MODULES=NULL
                                "STATIC_util_str_escape_MODULES_PROTO=extern void __util_str_escape_dummy_module_proto(void)"
                                STATIC_common_auth_MODULES=NULL
                                "STATIC_common_auth_MODULES_PROTO=extern void __common_auth_dummy_module_proto(void)"
)

target_compile_options (${TARGET_NAME}_obj PRIVATE -MMD -fPIC -fstack-protector-strong ${GCCDEFS})
