set (TARGET_NAME gssapi)

set (TARGET_SRC
     ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi/asn1_gssapi_asn1.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/spnego/init_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/spnego/external.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/spnego/compat.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/spnego/context_stubs.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/spnego/cred_stubs.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/spnego/accept_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/copy_ccache.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/delete_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/init_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/context_time.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/init.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/address_to_krb5addr.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/get_mic.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/inquire_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/add_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/inquire_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/inquire_cred_by_oid.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/inquire_cred_by_mech.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/inquire_mechs_for_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/inquire_names_for_mech.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/indicate_mechs.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/inquire_sec_context_by_oid.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/export_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/import_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/duplicate_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/import_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/compare_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/export_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/canonicalize_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/unwrap.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/wrap.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/release_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/cfx.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/8003.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/arcfour.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/encapsulate.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/display_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/sequence.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/display_status.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/release_buffer.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/external.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/compat.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/creds.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/acquire_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/release_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/store_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/set_cred_option.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/decapsulate.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/verify_mic.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/accept_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/set_sec_context_option.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/process_context_token.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/prf.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/aeap.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/pname_to_uid.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5/authorize_localname.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_krb5.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_mech_switch.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_process_context_token.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_buffer_set.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_aeap.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_add_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_add_oid_set_member.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_compare_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_release_oid_set.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_create_empty_oid_set.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_decapsulate_token.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_inquire_cred_by_oid.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_canonicalize_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_inquire_sec_context_by_oid.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_inquire_names_for_mech.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_inquire_mechs_for_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_wrap_size_limit.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_names.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_verify.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_display_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_duplicate_oid.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_display_status.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_release_buffer.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_release_oid.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_test_oid_set_member.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_release_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_set_sec_context_option.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_export_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_seal.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_acquire_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_unseal.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_verify_mic.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_accept_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_inquire_cred_by_mech.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_indicate_mechs.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_delete_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_sign.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_utils.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_init_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_oid_equal.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_oid.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_oid_to_str.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_mo.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_context_time.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_encapsulate_token.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_get_mic.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_import_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_inquire_cred.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_wrap.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_import_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_duplicate_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_unwrap.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_export_sec_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_inquire_context.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_release_name.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_set_cred_option.c
     ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech/gss_pseudo_random.c
     ${SMB_SRC_ROOT}/source4/heimdal_build/gssapi-glue.c
     ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi/asn1_spnego_asn1.c)

add_library (${TARGET_NAME}_obj OBJECT ${TARGET_SRC})

target_include_directories (${TARGET_NAME}_obj
                            PRIVATE
                                ${SMB_SRC_ROOT}/source4/heimdal_build
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal_build
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/asn1
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/asn1
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi
                                ${SMB_SRC_ROOT}/include/public
                                ${SMB_SRC_ROOT}/bin/default/include/public
                                ${SMB_SRC_ROOT}/source4
                                ${SMB_SRC_ROOT}/bin/default/source4
                                ${SMB_SRC_ROOT}/lib
                                ${SMB_SRC_ROOT}/bin/default/lib
                                ${SMB_SRC_ROOT}/source4/lib
                                ${SMB_SRC_ROOT}/bin/default/source4/lib
                                ${SMB_SRC_ROOT}/source4/include
                                ${SMB_SRC_ROOT}/bin/default/source4/include
                                ${SMB_SRC_ROOT}/include
                                ${SMB_SRC_ROOT}/bin/default/include
                                ${SMB_SRC_ROOT}/lib/replace
                                ${SMB_SRC_ROOT}/bin/default/lib/replace
                                ${SMB_SRC_ROOT}/.
                                ${SMB_SRC_ROOT}/bin/default/
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/roken
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/roken
                                ${SMB_SRC_ROOT}/source4/heimdal/include
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/include
                                ${SMB_SRC_ROOT}/source4/heimdal_build/include
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal_build/include
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/gssapi
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi/gssapi
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/spnego
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi/spnego
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/krb5
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi/krb5
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/gssapi/mech
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/gssapi/mech
                                ${SMB_SRC_ROOT}/source4/heimdal/base
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/base
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/hx509
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/hx509
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/wind
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/wind
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/krb5
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/krb5
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/hcrypto
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/hcrypto
                                ${SMB_SRC_ROOT}/source4/heimdal/lib
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/hcrypto/libtommath
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/hcrypto/libtommath
                                ${SMB_SRC_ROOT}/source4/heimdal/lib/com_err
                                ${SMB_SRC_ROOT}/bin/default/source4/heimdal/lib/com_err)

target_compile_definitions (${TARGET_NAME}_obj
                            PRIVATE
                                _SAMBA_BUILD_=4
                                HAVE_CONFIG_H=1
                                _GNU_SOURCE=1
                                _XOPEN_SOURCE_EXTENDED=1
                                __STDC_WANT_LIB_EXT1__=1
                                _REENTRANT
                                _POSIX_PTHREAD_SEMANTICS
                                STATIC_HEIMDAL_GSSAPI_ASN1_MODULES=NULL
                                "STATIC_HEIMDAL_GSSAPI_ASN1_MODULES_PROTO=extern void __HEIMDAL_GSSAPI_ASN1_dummy_module_proto(void)"
                                STATIC_gssapi_MODULES=NULL
                                "STATIC_gssapi_MODULES_PROTO=extern void __gssapi_dummy_module_proto(void)"
                                STATIC_HEIMDAL_SPNEGO_ASN1_MODULES=NULL
                                "STATIC_HEIMDAL_SPNEGO_ASN1_MODULES_PROTO=extern void __HEIMDAL_SPNEGO_ASN1_dummy_module_proto(void)"
)

target_compile_options (${TARGET_NAME}_obj
                        PRIVATE -MMD
                                -fPIC
                                -fstack-protector-strong
                                ${GCCDEFS}
                                -Wno-error=discarded-qualifiers
                                -Wno-error=cast-qual
                                -Wno-error=missing-field-initializers
                                -Wno-error=shadow
                                -Wno-error=implicit-fallthrough
                                -Wno-error=enum-compare
                                -Wno-error=unused-but-set-variable
                                -Wno-error=unused-const-variable
                                -Wno-error=unused-variable
                                -Wno-error=unused-result)
